/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthAccountRouteImport } from './routes/_auth/account'
import { Route as AuthTulesIndexRouteImport } from './routes/_auth/tules/index'
import { Route as AuthTheoryIndexRouteImport } from './routes/_auth/theory/index'
import { Route as AuthExamsIndexRouteImport } from './routes/_auth/exams/index'
import { Route as AuthAccountIndexRouteImport } from './routes/_auth/account/index'
import { Route as AuthTheoryLearnKoreanRouteImport } from './routes/_auth/theory/learn-korean'
import { Route as AuthExamsExamIdRouteImport } from './routes/_auth/exams/$examId'
import { Route as AuthAccountEditRouteImport } from './routes/_auth/account/edit'
import { Route as AuthTulesTulIdIndexRouteImport } from './routes/_auth/tules/$tulId/index'
import { Route as AuthTulesTulIdVideoRouteImport } from './routes/_auth/tules/$tulId/video'
import { Route as AuthTheoryBlockIdRouteImport } from './routes/_auth/theory/block.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTulesIndexRoute = AuthTulesIndexRouteImport.update({
  id: '/tules/',
  path: '/tules/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTheoryIndexRoute = AuthTheoryIndexRouteImport.update({
  id: '/theory/',
  path: '/theory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExamsIndexRoute = AuthExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountIndexRoute = AuthAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthTheoryLearnKoreanRoute = AuthTheoryLearnKoreanRouteImport.update({
  id: '/theory/learn-korean',
  path: '/theory/learn-korean',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExamsExamIdRoute = AuthExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountEditRoute = AuthAccountEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthTulesTulIdIndexRoute = AuthTulesTulIdIndexRouteImport.update({
  id: '/tules/$tulId/',
  path: '/tules/$tulId/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTulesTulIdVideoRoute = AuthTulesTulIdVideoRouteImport.update({
  id: '/tules/$tulId/video',
  path: '/tules/$tulId/video',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTheoryBlockIdRoute = AuthTheoryBlockIdRouteImport.update({
  id: '/theory/block/$id',
  path: '/theory/block/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthAccountRouteWithChildren
  '/calendar': typeof AuthCalendarRoute
  '/account/edit': typeof AuthAccountEditRoute
  '/exams/$examId': typeof AuthExamsExamIdRoute
  '/theory/learn-korean': typeof AuthTheoryLearnKoreanRoute
  '/account/': typeof AuthAccountIndexRoute
  '/exams/': typeof AuthExamsIndexRoute
  '/theory/': typeof AuthTheoryIndexRoute
  '/tules/': typeof AuthTulesIndexRoute
  '/theory/block/$id': typeof AuthTheoryBlockIdRoute
  '/tules/$tulId/video': typeof AuthTulesTulIdVideoRoute
  '/tules/$tulId/': typeof AuthTulesTulIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AuthCalendarRoute
  '/': typeof AuthIndexRoute
  '/account/edit': typeof AuthAccountEditRoute
  '/exams/$examId': typeof AuthExamsExamIdRoute
  '/theory/learn-korean': typeof AuthTheoryLearnKoreanRoute
  '/account': typeof AuthAccountIndexRoute
  '/exams': typeof AuthExamsIndexRoute
  '/theory': typeof AuthTheoryIndexRoute
  '/tules': typeof AuthTulesIndexRoute
  '/theory/block/$id': typeof AuthTheoryBlockIdRoute
  '/tules/$tulId/video': typeof AuthTulesTulIdVideoRoute
  '/tules/$tulId': typeof AuthTulesTulIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/account': typeof AuthAccountRouteWithChildren
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/account/edit': typeof AuthAccountEditRoute
  '/_auth/exams/$examId': typeof AuthExamsExamIdRoute
  '/_auth/theory/learn-korean': typeof AuthTheoryLearnKoreanRoute
  '/_auth/account/': typeof AuthAccountIndexRoute
  '/_auth/exams/': typeof AuthExamsIndexRoute
  '/_auth/theory/': typeof AuthTheoryIndexRoute
  '/_auth/tules/': typeof AuthTulesIndexRoute
  '/_auth/theory/block/$id': typeof AuthTheoryBlockIdRoute
  '/_auth/tules/$tulId/video': typeof AuthTulesTulIdVideoRoute
  '/_auth/tules/$tulId/': typeof AuthTulesTulIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/calendar'
    | '/account/edit'
    | '/exams/$examId'
    | '/theory/learn-korean'
    | '/account/'
    | '/exams/'
    | '/theory/'
    | '/tules/'
    | '/theory/block/$id'
    | '/tules/$tulId/video'
    | '/tules/$tulId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/'
    | '/account/edit'
    | '/exams/$examId'
    | '/theory/learn-korean'
    | '/account'
    | '/exams'
    | '/theory'
    | '/tules'
    | '/theory/block/$id'
    | '/tules/$tulId/video'
    | '/tules/$tulId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/account'
    | '/_auth/calendar'
    | '/_auth/'
    | '/_auth/account/edit'
    | '/_auth/exams/$examId'
    | '/_auth/theory/learn-korean'
    | '/_auth/account/'
    | '/_auth/exams/'
    | '/_auth/theory/'
    | '/_auth/tules/'
    | '/_auth/theory/block/$id'
    | '/_auth/tules/$tulId/video'
    | '/_auth/tules/$tulId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tules/': {
      id: '/_auth/tules/'
      path: '/tules'
      fullPath: '/tules/'
      preLoaderRoute: typeof AuthTulesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/theory/': {
      id: '/_auth/theory/'
      path: '/theory'
      fullPath: '/theory/'
      preLoaderRoute: typeof AuthTheoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/exams/': {
      id: '/_auth/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthExamsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account/': {
      id: '/_auth/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthAccountIndexRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/theory/learn-korean': {
      id: '/_auth/theory/learn-korean'
      path: '/theory/learn-korean'
      fullPath: '/theory/learn-korean'
      preLoaderRoute: typeof AuthTheoryLearnKoreanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/exams/$examId': {
      id: '/_auth/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthExamsExamIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account/edit': {
      id: '/_auth/account/edit'
      path: '/edit'
      fullPath: '/account/edit'
      preLoaderRoute: typeof AuthAccountEditRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/tules/$tulId/': {
      id: '/_auth/tules/$tulId/'
      path: '/tules/$tulId'
      fullPath: '/tules/$tulId/'
      preLoaderRoute: typeof AuthTulesTulIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tules/$tulId/video': {
      id: '/_auth/tules/$tulId/video'
      path: '/tules/$tulId/video'
      fullPath: '/tules/$tulId/video'
      preLoaderRoute: typeof AuthTulesTulIdVideoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/theory/block/$id': {
      id: '/_auth/theory/block/$id'
      path: '/theory/block/$id'
      fullPath: '/theory/block/$id'
      preLoaderRoute: typeof AuthTheoryBlockIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthAccountRouteChildren {
  AuthAccountEditRoute: typeof AuthAccountEditRoute
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute
}

const AuthAccountRouteChildren: AuthAccountRouteChildren = {
  AuthAccountEditRoute: AuthAccountEditRoute,
  AuthAccountIndexRoute: AuthAccountIndexRoute,
}

const AuthAccountRouteWithChildren = AuthAccountRoute._addFileChildren(
  AuthAccountRouteChildren,
)

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRouteWithChildren
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthExamsExamIdRoute: typeof AuthExamsExamIdRoute
  AuthTheoryLearnKoreanRoute: typeof AuthTheoryLearnKoreanRoute
  AuthExamsIndexRoute: typeof AuthExamsIndexRoute
  AuthTheoryIndexRoute: typeof AuthTheoryIndexRoute
  AuthTulesIndexRoute: typeof AuthTulesIndexRoute
  AuthTheoryBlockIdRoute: typeof AuthTheoryBlockIdRoute
  AuthTulesTulIdVideoRoute: typeof AuthTulesTulIdVideoRoute
  AuthTulesTulIdIndexRoute: typeof AuthTulesTulIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRouteWithChildren,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthExamsExamIdRoute: AuthExamsExamIdRoute,
  AuthTheoryLearnKoreanRoute: AuthTheoryLearnKoreanRoute,
  AuthExamsIndexRoute: AuthExamsIndexRoute,
  AuthTheoryIndexRoute: AuthTheoryIndexRoute,
  AuthTulesIndexRoute: AuthTulesIndexRoute,
  AuthTheoryBlockIdRoute: AuthTheoryBlockIdRoute,
  AuthTulesTulIdVideoRoute: AuthTulesTulIdVideoRoute,
  AuthTulesTulIdIndexRoute: AuthTulesTulIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
